"""Document preview and download helpers (demo — synthetic content from vault metadata)."""
from __future__ import annotations

from fastapi import HTTPException

from .store import store
from .schemas import Document


def _find(user_id: str, doc_id: str) -> Document:
    doc = store.get_document(user_id, doc_id)
    if not doc:
        raise HTTPException(404, "Document not found")
    return doc


def _vehicle_label(user_id: str, vehicle_id: str | None) -> str | None:
    if not vehicle_id:
        return None
    v = store.get_vehicle(user_id, vehicle_id)
    if not v:
        return vehicle_id
    return f"{v.make} {v.model} ({v.registration_number})"


def build_preview_text(user_id: str, doc: Document) -> str:
    v = store.get_vehicle(user_id, doc.vehicle_id) if doc.vehicle_id else None
    lines = [
        "VAAHAN SAARTHI DOCUMENT VAULT — PREVIEW",
        "=" * 42,
        f"Title: {doc.title}",
        f"Type: {doc.type}",
        f"Category: {doc.category}",
        f"Status: {doc.status.upper()}",
        f"Verified: {'Yes' if doc.verified else 'No'}",
    ]
    if doc.issue_date:
        lines.append(f"Issued: {doc.issue_date}")
    if doc.expiry_date:
        lines.append(f"Expires: {doc.expiry_date}")
    if v:
        lines.extend([
            "",
            "Linked vehicle:",
            f"  {v.make} {v.model} ({v.registration_number})",
            f"  Owner: {v.owner_name} · RTO: {v.rto}",
        ])
    lines.extend([
        "",
        "— Demo preview generated by Vaahan Saarthi. Not an official government record.",
    ])
    return "\n".join(lines)


def document_detail(user_id: str, doc_id: str) -> dict:
    doc = _find(user_id, doc_id)
    preview = build_preview_text(user_id, doc)
    return {
        "document": doc,
        "vehicle_label": _vehicle_label(user_id, doc.vehicle_id),
        "preview": preview,
        "filename": download_filename(doc),
    }


def download_filename(doc: Document) -> str:
    safe = doc.title.replace(" ", "_").replace("/", "-")[:40]
    return f"VaahanSaarthi_{doc.type}_{safe}.txt"


def download_bytes(user_id: str, doc_id: str) -> tuple[bytes, str]:
    doc = _find(user_id, doc_id)
    content = build_preview_text(user_id, doc).encode("utf-8")
    return content, download_filename(doc)
